const timezones = [
    { id: "Africa/Abidjan", country: "Ivory Coast", region: "Africa" },
    { id: "Africa/Accra", country: "Ghana", region: "Africa" },
    { id: "Africa/Addis_Ababa", country: "Ethiopia", region: "Africa" },
    { id: "Africa/Algiers", country: "Algeria", region: "Africa" },
    { id: "Africa/Asmara", country: "Eritrea", region: "Africa" },
    { id: "Africa/Bamako", country: "Mali", region: "Africa" },
    { id: "Africa/Bangui", country: "Central African Republic", region: "Africa" },
    { id: "Africa/Banjul", country: "Gambia", region: "Africa" },
    { id: "Africa/Bissau", country: "Guinea-Bissau", region: "Africa" },
    { id: "Africa/Blantyre", country: "Malawi", region: "Africa" },
    { id: "Africa/Brazzaville", country: "Republic of the Congo", region: "Africa" },
    { id: "Africa/Bujumbura", country: "Burundi", region: "Africa" },
    { id: "Africa/Cairo", country: "Egypt", region: "Africa" },
    { id: "Africa/Casablanca", country: "Morocco", region: "Africa" },
    { id: "Africa/Ceuta", country: "Spain", region: "Africa" },
    { id: "Africa/Conakry", country: "Guinea", region: "Africa" },
    { id: "Africa/Dakar", country: "Senegal", region: "Africa" },
    { id: "Africa/Dar_es_Salaam", country: "Tanzania", region: "Africa" },
    { id: "Africa/Djibouti", country: "Djibouti", region: "Africa" },
    { id: "Africa/Douala", country: "Cameroon", region: "Africa" },
    { id: "Africa/El_Aaiun", country: "Western Sahara", region: "Africa" },
    { id: "Africa/Freetown", country: "Sierra Leone", region: "Africa" },
    { id: "Africa/Gaborone", country: "Botswana", region: "Africa" },
    { id: "Africa/Harare", country: "Zimbabwe", region: "Africa" },
    { id: "Africa/Johannesburg", country: "South Africa", region: "Africa" },
    { id: "Africa/Juba", country: "South Sudan", region: "Africa" },
    { id: "Africa/Kampala", country: "Uganda", region: "Africa" },
    { id: "Africa/Khartoum", country: "Sudan", region: "Africa" },
    { id: "Africa/Kigali", country: "Rwanda", region: "Africa" },
    { id: "Africa/Kinshasa", country: "Democratic Republic of the Congo", region: "Africa" },
    { id: "Africa/Lagos", country: "Nigeria", region: "Africa" },
    { id: "Africa/Libreville", country: "Gabon", region: "Africa" },
    { id: "Africa/Lome", country: "Togo", region: "Africa" },
    { id: "Africa/Luanda", country: "Angola", region: "Africa" },
    { id: "Africa/Lubumbashi", country: "Democratic Republic of the Congo", region: "Africa" },
    { id: "Africa/Lusaka", country: "Zambia", region: "Africa" },
    { id: "Africa/Malabo", country: "Equatorial Guinea", region: "Africa" },
    { id: "Africa/Maputo", country: "Mozambique", region: "Africa" },
    { id: "Africa/Maseru", country: "Lesotho", region: "Africa" },
    { id: "Africa/Mbabane", country: "Eswatini", region: "Africa" },
    { id: "Africa/Mogadishu", country: "Somalia", region: "Africa" },
    { id: "Africa/Monrovia", country: "Liberia", region: "Africa" },
    { id: "Africa/Nairobi", country: "Kenya", region: "Africa" },
    { id: "Africa/Ndjamena", country: "Chad", region: "Africa" },
    { id: "Africa/Niamey", country: "Niger", region: "Africa" },
    { id: "Africa/Nouakchott", country: "Mauritania", region: "Africa" },
    { id: "Africa/Ouagadougou", country: "Burkina Faso", region: "Africa" },
    { id: "Africa/Porto-Novo", country: "Benin", region: "Africa" },
    { id: "Africa/Sao_Tome", country: "Sao Tome and Principe", region: "Africa" },
    { id: "Africa/Tripoli", country: "Libya", region: "Africa" },
    { id: "Africa/Tunis", country: "Tunisia", region: "Africa" },
    { id: "Africa/Windhoek", country: "Namibia", region: "Africa" },
    { id: "America/Adak", country: "United States", region: "North America" },
    { id: "America/Anchorage", country: "United States", region: "North America" },
    { id: "America/Anguilla", country: "Anguilla", region: "North America" },
    { id: "America/Antigua", country: "Antigua and Barbuda", region: "North America" },
    { id: "America/Araguaina", country: "Brazil", region: "South America" },
    { id: "America/Argentina/Buenos_Aires", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Catamarca", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Cordoba", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Jujuy", country: "Argentina", region: "South America" },
    { id: "America/Argentina/La_Rioja", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Mendoza", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Rio_Gallegos", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Salta", country: "Argentina", region: "South America" },
    { id: "America/Argentina/San_Juan", country: "Argentina", region: "South America" },
    { id: "America/Argentina/San_Luis", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Tucuman", country: "Argentina", region: "South America" },
    { id: "America/Argentina/Ushuaia", country: "Argentina", region: "South America" },
    { id: "America/Aruba", country: "Aruba", region: "North America" },
    { id: "America/Asuncion", country: "Paraguay", region: "South America" },
    { id: "America/Atikokan", country: "Canada", region: "North America" },
    { id: "America/Bahia", country: "Brazil", region: "South America" },
    { id: "America/Bahia_Banderas", country: "Mexico", region: "North America" },
    { id: "America/Barbados", country: "Barbados", region: "North America" },
    { id: "America/Belem", country: "Brazil", region: "South America" },
    { id: "America/Belize", country: "Belize", region: "North America" },
    { id: "America/Blanc-Sablon", country: "Canada", region: "North America" },
    { id: "America/Boa_Vista", country: "Brazil", region: "South America" },
    { id: "America/Bogota", country: "Colombia", region: "South America" },
    { id: "America/Boise", country: "United States", region: "North America" },
    { id: "America/Cambridge_Bay", country: "Canada", region: "North America" },
    { id: "America/Campo_Grande", country: "Brazil", region: "South America" },
    { id: "America/Cancun", country: "Mexico", region: "North America" },
    { id: "America/Caracas", country: "Venezuela", region: "South America" },
    { id: "America/Cayenne", country: "French Guiana", region: "South America" },
    { id: "America/Cayman", country: "Cayman Islands", region: "North America" },
    { id: "America/Chicago", country: "United States", region: "North America" },
    { id: "America/Chihuahua", country: "Mexico", region: "North America" },
    { id: "America/Costa_Rica", country: "Costa Rica", region: "North America" },
    { id: "America/Creston", country: "Canada", region: "North America" },
    { id: "America/Cuiaba", country: "Brazil", region: "South America" },
    { id: "America/Curacao", country: "Curaçao", region: "North America" },
    { id: "America/Danmarkshavn", country: "Greenland", region: "North America" },
    { id: "America/Dawson", country: "Canada", region: "North America" },
    { id: "America/Dawson_Creek", country: "Canada", region: "North America" },
    { id: "America/Denver", country: "United States", region: "North America" },
    { id: "America/Detroit", country: "United States", region: "North America" },
    { id: "America/Dominica", country: "Dominica", region: "North America" },
    { id: "America/Edmonton", country: "Canada", region: "North America" },
    { id: "America/Eirunepe", country: "Brazil", region: "South America" },
    { id: "America/El_Salvador", country: "El Salvador", region: "North America" },
    { id: "America/Fort_Nelson", country: "Canada", region: "North America" },
    { id: "America/Fortaleza", country: "Brazil", region: "South America" },
    { id: "America/Glace_Bay", country: "Canada", region: "North America" },
    { id: "America/Godthab", country: "Greenland", region: "North America" },
    { id: "America/Goose_Bay", country: "Canada", region: "North America" },
    { id: "America/Grand_Turk", country: "Turks and Caicos Islands", region: "North America" },
    { id: "America/Grenada", country: "Grenada", region: "North America" },
    { id: "America/Guadeloupe", country: "Guadeloupe", region: "North America" },
    { id: "America/Guatemala", country: "Guatemala", region: "North America" },
    { id: "America/Guayaquil", country: "Ecuador", region: "South America" },
    { id: "America/Guyana", country: "Guyana", region: "South America" },
    { id: "America/Halifax", country: "Canada", region: "North America" },
    { id: "America/Havana", country: "Cuba", region: "North America" },
    { id: "America/Hermosillo", country: "Mexico", region: "North America" },
    { id: "America/Indiana/Indianapolis", country: "United States", region: "North America" },
    { id: "America/Indiana/Knox", country: "United States", region: "North America" },
    { id: "America/Indiana/Marengo", country: "United States", region: "North America" },
    { id: "America/Indiana/Petersburg", country: "United States", region: "North America" },
    { id: "America/Indiana/Tell_City", country: "United States", region: "North America" },
    { id: "America/Indiana/Vevay", country: "United States", region: "North America" },
    { id: "America/Indiana/Vincennes", country: "United States", region: "North America" },
    { id: "America/Indiana/Winamac", country: "United States", region: "North America" },
    { id: "America/Inuvik", country: "Canada", region: "North America" },
    { id: "America/Iqaluit", country: "Canada", region: "North America" },
    { id: "America/Jamaica", country: "Jamaica", region: "North America" },
    { id: "America/Juneau", country: "United States", region: "North America" },
    { id: "America/Kentucky/Louisville", country: "United States", region: "North America" },
    { id: "America/Kentucky/Monticello", country: "United States", region: "North America" },
    { id: "America/Kralendijk", country: "Bonaire", region: "North America" },
    { id: "America/La_Paz", country: "Bolivia", region: "South America" },
    { id: "America/Lima", country: "Peru", region: "South America" },
    { id: "America/Los_Angeles", country: "United States", region: "North America" },
    { id: "America/Lower_Princes", country: "Sint Maarten", region: "North America" },
    { id: "America/Maceio", country: "Brazil", region: "South America" },
    { id: "America/Managua", country: "Nicaragua", region: "North America" },
    { id: "America/Manaus", country: "Brazil", region: "South America" },
    { id: "America/Marigot", country: "Saint Martin", region: "North America" },
    { id: "America/Martinique", country: "Martinique", region: "North America" },
    { id: "America/Matamoros", country: "Mexico", region: "North America" },
    { id: "America/Mazatlan", country: "Mexico", region: "North America" },
    { id: "America/Menominee", country: "United States", region: "North America" },
    { id: "America/Merida", country: "Mexico", region: "North America" },
    { id: "America/Metlakatla", country: "United States", region: "North America" },
    { id: "America/Mexico_City", country: "Mexico", region: "North America" },
    { id: "America/Miquelon", country: "Saint Pierre and Miquelon", region: "North America" },
    { id: "America/Moncton", country: "Canada", region: "North America" },
    { id: "America/Monterrey", country: "Mexico", region: "North America" },
    { id: "America/Montevideo", country: "Uruguay", region: "South America" },
    { id: "America/Montserrat", country: "Montserrat", region: "North America" },
    { id: "America/Nassau", country: "Bahamas", region: "North America" },
    { id: "America/New_York", country: "United States", region: "North America" },
    { id: "America/Nipigon", country: "Canada", region: "North America" },
    { id: "America/Nome", country: "United States", region: "North America" },
    { id: "America/Noronha", country: "Brazil", region: "South America" },
    { id: "America/North_Dakota/Beulah", country: "United States", region: "North America" },
    { id: "America/North_Dakota/Center", country: "United States", region: "North America" },
    { id: "America/North_Dakota/New_Salem", country: "United States", region: "North America" },
    { id: "America/Ojinaga", country: "Mexico", region: "North America" },
    { id: "America/Panama", country: "Panama", region: "North America" },
    { id: "America/Pangnirtung", country: "Canada", region: "North America" },
    { id: "America/Paramaribo", country: "Suriname", region: "South America" },
    { id: "America/Phoenix", country: "United States", region: "North America" },
    { id: "America/Port-au-Prince", country: "Haiti", region: "North America" },
    { id: "America/Port_of_Spain", country: "Trinidad and Tobago", region: "North America" },
    { id: "America/Porto_Velho", country: "Brazil", region: "South America" },
    { id: "America/Puerto_Rico", country: "Puerto Rico", region: "North America" },
    { id: "America/Punta_Arenas", country: "Chile", region: "South America" },
    { id: "America/Rainy_River", country: "Canada", region: "North America" },
    { id: "America/Rankin_Inlet", country: "Canada", region: "North America" },
    { id: "America/Recife", country: "Brazil", region: "South America" },
    { id: "America/Regina", country: "Canada", region: "North America" },
    { id: "America/Resolute", country: "Canada", region: "North America" },
    { id: "America/Rio_Branco", country: "Brazil", region: "South America" },
    { id: "America/Santarem", country: "Brazil", region: "South America" },
    { id: "America/Santiago", country: "Chile", region: "South America" },
    { id: "America/Santo_Domingo", country: "Dominican Republic", region: "North America" },
    { id: "America/Sao_Paulo", country: "Brazil", region: "South America" },
    { id: "America/Scoresbysund", country: "Greenland", region: "North America" },
    { id: "America/Sitka", country: "United States", region: "North America" },
    { id: "America/St_Barthelemy", country: "Saint Barthélemy", region: "North America" },
    { id: "America/St_Johns", country: "Canada", region: "North America" },
    { id: "America/St_Kitts", country: "Saint Kitts and Nevis", region: "North America" },
    { id: "America/St_Lucia", country: "Saint Lucia", region: "North America" },
    { id: "America/St_Thomas", country: "U.S. Virgin Islands", region: "North America" },
    { id: "America/St_Vincent", country: "Saint Vincent and the Grenadines", region: "North America" },
    { id: "America/Swift_Current", country: "Canada", region: "North America" },
    { id: "America/Tegucigalpa", country: "Honduras", region: "North America" },
    { id: "America/Thule", country: "Greenland", region: "North America" },
    { id: "America/Thunder_Bay", country: "Canada", region: "North America" },
    { id: "America/Tijuana", country: "Mexico", region: "North America" },
    { id: "America/Toronto", country: "Canada", region: "North America" },
    { id: "America/Tortola", country: "British Virgin Islands", region: "North America" },
    { id: "America/Vancouver", country: "Canada", region: "North America" },
    { id: "America/Whitehorse", country: "Canada", region: "North America" },
    { id: "America/Winnipeg", country: "Canada", region: "North America" },
    { id: "America/Yakutat", country: "United States", region: "North America" },
    { id: "America/Yellowknife", country: "Canada", region: "North America" },
    { id: "Antarctica/Casey", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Davis", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/DumontDUrville", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Macquarie", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Mawson", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/McMurdo", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Palmer", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Rothera", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Syowa", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Troll", country: "Antarctica", region: "Antarctica" },
    { id: "Antarctica/Vostok", country: "Antarctica", region: "Antarctica" },
    { id: "Asia/Aden", country: "Yemen", region: "Asia" },
    { id: "Asia/Almaty", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Amman", country: "Jordan", region: "Asia" },
    { id: "Asia/Anadyr", country: "Russia", region: "Asia" },
    { id: "Asia/Aqtau", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Aqtobe", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Ashgabat", country: "Turkmenistan", region: "Asia" },
    { id: "Asia/Atyrau", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Baghdad", country: "Iraq", region: "Asia" },
    { id: "Asia/Bahrain", country: "Bahrain", region: "Asia" },
    { id: "Asia/Baku", country: "Azerbaijan", region: "Asia" },
    { id: "Asia/Bangkok", country: "Thailand", region: "Asia" },
    { id: "Asia/Barnaul", country: "Russia", region: "Asia" },
    { id: "Asia/Beirut", country: "Lebanon", region: "Asia" },
    { id: "Asia/Bishkek", country: "Kyrgyzstan", region: "Asia" },
    { id: "Asia/Brunei", country: "Brunei", region: "Asia" },
    { id: "Asia/Chita", country: "Russia", region: "Asia" },
    { id: "Asia/Choibalsan", country: "Mongolia", region: "Asia" },
    { id: "Asia/Colombo", country: "Sri Lanka", region: "Asia" },
    { id: "Asia/Damascus", country: "Syria", region: "Asia" },
    { id: "Asia/Dhaka", country: "Bangladesh", region: "Asia" },
    { id: "Asia/Dili", country: "East Timor", region: "Asia" },
    { id: "Asia/Dubai", country: "United Arab Emirates", region: "Asia" },
    { id: "Asia/Dushanbe", country: "Tajikistan", region: "Asia" },
    { id: "Asia/Famagusta", country: "Cyprus", region: "Asia" },
    { id: "Asia/Gaza", country: "Palestine", region: "Asia" },
    { id: "Asia/Hebron", country: "Palestine", region: "Asia" },
    { id: "Asia/Ho_Chi_Minh", country: "Vietnam", region: "Asia" },
    { id: "Asia/Hong_Kong", country: "Hong Kong", region: "Asia" },
    { id: "Asia/Hovd", country: "Mongolia", region: "Asia" },
    { id: "Asia/Irkutsk", country: "Russia", region: "Asia" },
    { id: "Asia/Jakarta", country: "Indonesia", region: "Asia" },
    { id: "Asia/Jayapura", country: "Indonesia", region: "Asia" },
    { id: "Asia/Jerusalem", country: "Israel", region: "Asia" },
    { id: "Asia/Kabul", country: "Afghanistan", region: "Asia" },
    { id: "Asia/Kamchatka", country: "Russia", region: "Asia" },
    { id: "Asia/Karachi", country: "Pakistan", region: "Asia" },
    { id: "Asia/Kathmandu", country: "Nepal", region: "Asia" },
    { id: "Asia/Khandyga", country: "Russia", region: "Asia" },
    { id: "Asia/Kolkata", country: "India", region: "Asia" },
    { id: "Asia/Krasnoyarsk", country: "Russia", region: "Asia" },
    { id: "Asia/Kuala_Lumpur", country: "Malaysia", region: "Asia" },
    { id: "Asia/Kuching", country: "Malaysia", region: "Asia" },
    { id: "Asia/Kuwait", country: "Kuwait", region: "Asia" },
    { id: "Asia/Macau", country: "Macau", region: "Asia" },
    { id: "Asia/Magadan", country: "Russia", region: "Asia" },
    { id: "Asia/Makassar", country: "Indonesia", region: "Asia" },
    { id: "Asia/Manila", country: "Philippines", region: "Asia" },
    { id: "Asia/Muscat", country: "Oman", region: "Asia" },
    { id: "Asia/Nicosia", country: "Cyprus", region: "Asia" },
    { id: "Asia/Novokuznetsk", country: "Russia", region: "Asia" },
    { id: "Asia/Novosibirsk", country: "Russia", region: "Asia" },
    { id: "Asia/Omsk", country: "Russia", region: "Asia" },
    { id: "Asia/Oral", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Phnom_Penh", country: "Cambodia", region: "Asia" },
    { id: "Asia/Pontianak", country: "Indonesia", region: "Asia" },
    { id: "Asia/Pyongyang", country: "North Korea", region: "Asia" },
    { id: "Asia/Qatar", country: "Qatar", region: "Asia" },
    { id: "Asia/Qostanay", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Qyzylorda", country: "Kazakhstan", region: "Asia" },
    { id: "Asia/Riyadh", country: "Saudi Arabia", region: "Asia" },
    { id: "Asia/Sakhalin", country: "Russia", region: "Asia" },
    { id: "Asia/Samarkand", country: "Uzbekistan", region: "Asia" },
    { id: "Asia/Seoul", country: "South Korea", region: "Asia" },
    { id: "Asia/Shanghai", country: "China", region: "Asia" },
    { id: "Asia/Singapore", country: "Singapore", region: "Asia" },
    { id: "Asia/Srednekolymsk", country: "Russia", region: "Asia" },
    { id: "Asia/Taipei", country: "Taiwan", region: "Asia" },
    { id: "Asia/Tashkent", country: "Uzbekistan", region: "Asia" },
    { id: "Asia/Tbilisi", country: "Georgia", region: "Asia" },
    { id: "Asia/Tehran", country: "Iran", region: "Asia" },
    { id: "Asia/Thimphu", country: "Bhutan", region: "Asia" },
    { id: "Asia/Tokyo", country: "Japan", region: "Asia" },
    { id: "Asia/Tomsk", country: "Russia", region: "Asia" },
    { id: "Asia/Ulaanbaatar", country: "Mongolia", region: "Asia" },
    { id: "Asia/Urumqi", country: "China", region: "Asia" },
    { id: "Asia/Ust-Nera", country: "Russia", region: "Asia" },
    { id: "Asia/Vientiane", country: "Laos", region: "Asia" },
    { id: "Asia/Vladivostok", country: "Russia", region: "Asia" },
    { id: "Asia/Yakutsk", country: "Russia", region: "Asia" },
    { id: "Asia/Yangon", country: "Myanmar", region: "Asia" },
    { id: "Asia/Yekaterinburg", country: "Russia", region: "Asia" },
    { id: "Asia/Yerevan", country: "Armenia", region: "Asia" },
    { id: "Atlantic/Azores", country: "Portugal", region: "Atlantic" },
    { id: "Atlantic/Bermuda", country: "Bermuda", region: "Atlantic" },
    { id: "Atlantic/Canary", country: "Spain", region: "Atlantic" },
    { id: "Atlantic/Cape_Verde", country: "Cape Verde", region: "Atlantic" },
    { id: "Atlantic/Faroe", country: "Faroe Islands", region: "Atlantic" },
    { id: "Atlantic/Madeira", country: "Portugal", region: "Atlantic" },
    { id: "Atlantic/Reykjavik", country: "Iceland", region: "Atlantic" },
    { id: "Atlantic/South_Georgia", country: "South Georgia and the South Sandwich Islands", region: "Atlantic" },
    { id: "Atlantic/St_Helena", country: "Saint Helena", region: "Atlantic" },
    { id: "Atlantic/Stanley", country: "Falkland Islands", region: "Atlantic" },
    { id: "Australia/Adelaide", country: "Australia", region: "Australia" },
    { id: "Australia/Brisbane", country: "Australia", region: "Australia" },
    { id: "Australia/Broken_Hill", country: "Australia", region: "Australia" },
    { id: "Australia/Darwin", country: "Australia", region: "Australia" },
    { id: "Australia/Eucla", country: "Australia", region: "Australia" },
    { id: "Australia/Hobart", country: "Australia", region: "Australia" },
    { id: "Australia/Lindeman", country: "Australia", region: "Australia" },
    { id: "Australia/Lord_Howe", country: "Australia", region: "Australia" },
    { id: "Australia/Melbourne", country: "Australia", region: "Australia" },
    { id: "Australia/Perth", country: "Australia", region: "Australia" },
    { id: "Australia/Sydney", country: "Australia", region: "Australia" },
    { id: "Europe/Amsterdam", country: "Netherlands", region: "Europe" },
    { id: "Europe/Andorra", country: "Andorra", region: "Europe" },
    { id: "Europe/Astrakhan", country: "Russia", region: "Europe" },
    { id: "Europe/Athens", country: "Greece", region: "Europe" },
    { id: "Europe/Belgrade", country: "Serbia", region: "Europe" },
    { id: "Europe/Berlin", country: "Germany", region: "Europe" },
    { id: "Europe/Bratislava", country: "Slovakia", region: "Europe" },
    { id: "Europe/Brussels", country: "Belgium", region: "Europe" },
    { id: "Europe/Bucharest", country: "Romania", region: "Europe" },
    { id: "Europe/Budapest", country: "Hungary", region: "Europe" },
    { id: "Europe/Busingen", country: "Germany", region: "Europe" },
    { id: "Europe/Chisinau", country: "Moldova", region: "Europe" },
    { id: "Europe/Copenhagen", country: "Denmark", region: "Europe" },
    { id: "Europe/Dublin", country: "Ireland", region: "Europe" },
    { id: "Europe/Gibraltar", country: "Gibraltar", region: "Europe" },
    { id: "Europe/Guernsey", country: "Guernsey", region: "Europe" },
    { id: "Europe/Helsinki", country: "Finland", region: "Europe" },
    { id: "Europe/Isle_of_Man", country: "Isle of Man", region: "Europe" },
    { id: "Europe/Istanbul", country: "Turkey", region: "Europe" },
    { id: "Europe/Jersey", country: "Jersey", region: "Europe" },
    { id: "Europe/Kaliningrad", country: "Russia", region: "Europe" },
    { id: "Europe/Kiev", country: "Ukraine", region: "Europe" },
    { id: "Europe/Kirov", country: "Russia", region: "Europe" },
    { id: "Europe/Lisbon", country: "Portugal", region: "Europe" },
    { id: "Europe/Ljubljana", country: "Slovenia", region: "Europe" },
    { id: "Europe/London", country: "United Kingdom", region: "Europe" },
    { id: "Europe/Luxembourg", country: "Luxembourg", region: "Europe" },
    { id: "Europe/Madrid", country: "Spain", region: "Europe" },
    { id: "Europe/Malta", country: "Malta", region: "Europe" },
    { id: "Europe/Mariehamn", country: "Åland Islands", region: "Europe" },
    { id: "Europe/Minsk", country: "Belarus", region: "Europe" },
    { id: "Europe/Monaco", country: "Monaco", region: "Europe" },
    { id: "Europe/Moscow", country: "Russia", region: "Europe" },
    { id: "Europe/Oslo", country: "Norway", region: "Europe" },
    { id: "Europe/Paris", country: "France", region: "Europe" },
    { id: "Europe/Podgorica", country: "Montenegro", region: "Europe" },
    { id: "Europe/Prague", country: "Czech Republic", region: "Europe" },
    { id: "Europe/Riga", country: "Latvia", region: "Europe" },
    { id: "Europe/Rome", country: "Italy", region: "Europe" },
    { id: "Europe/Samara", country: "Russia", region: "Europe" },
    { id: "Europe/San_Marino", country: "San Marino", region: "Europe" },
    { id: "Europe/Sarajevo", country: "Bosnia and Herzegovina", region: "Europe" },
    { id: "Europe/Saratov", country: "Russia", region: "Europe" },
    { id: "Europe/Simferopol", country: "Ukraine", region: "Europe" },
    { id: "Europe/Skopje", country: "North Macedonia", region: "Europe" },
    { id: "Europe/Sofia", country: "Bulgaria", region: "Europe" },
    { id: "Europe/Stockholm", country: "Sweden", region: "Europe" },
    { id: "Europe/Tallinn", country: "Estonia", region: "Europe" },
    { id: "Europe/Tirane", country: "Albania", region: "Europe" },
    { id: "Europe/Ulyanovsk", country: "Russia", region: "Europe" },
    { id: "Europe/Uzhgorod", country: "Ukraine", region: "Europe" },
    { id: "Europe/Vaduz", country: "Liechtenstein", region: "Europe" },
    { id: "Europe/Vatican", country: "Vatican City", region: "Europe" },
    { id: "Europe/Vienna", country: "Austria", region: "Europe" },
    { id: "Europe/Vilnius", country: "Lithuania", region: "Europe" },
    { id: "Europe/Volgograd", country: "Russia", region: "Europe" },
    { id: "Europe/Warsaw", country: "Poland", region: "Europe" },
    { id: "Europe/Zagreb", country: "Croatia", region: "Europe" },
    { id: "Europe/Zaporozhye", country: "Ukraine", region: "Europe" },
    { id: "Europe/Zurich", country: "Switzerland", region: "Europe" },
    { id: "Indian/Antananarivo", country: "Madagascar", region: "Indian Ocean" },
    { id: "Indian/Chagos", country: "British Indian Ocean Territory", region: "Indian Ocean" },
    { id: "Indian/Christmas", country: "Christmas Island", region: "Indian Ocean" },
    { id: "Indian/Cocos", country: "Cocos (Keeling) Islands", region: "Indian Ocean" },
    { id: "Indian/Comoro", country: "Comoros", region: "Indian Ocean" },
    { id: "Indian/Kerguelen", country: "French Southern Territories", region: "Indian Ocean" },
    { id: "Indian/Mahe", country: "Seychelles", region: "Indian Ocean" },
    { id: "Indian/Maldives", country: "Maldives", region: "Indian Ocean" },
    { id: "Indian/Mauritius", country: "Mauritius", region: "Indian Ocean" },
    { id: "Indian/Mayotte", country: "Mayotte", region: "Indian Ocean" },
    { id: "Indian/Reunion", country: "Réunion", region: "Indian Ocean" },
    { id: "Pacific/Apia", country: "Samoa", region: "Pacific" },
    { id: "Pacific/Auckland", country: "New Zealand", region: "Pacific" },
    { id: "Pacific/Bougainville", country: "Papua New Guinea", region: "Pacific" },
    { id: "Pacific/Chatham", country: "New Zealand", region: "Pacific" },
    { id: "Pacific/Chuuk", country: "Micronesia", region: "Pacific" },
    { id: "Pacific/Easter", country: "Chile", region: "Pacific" },
    { id: "Pacific/Efate", country: "Vanuatu", region: "Pacific" },
    { id: "Pacific/Enderbury", country: "Kiribati", region: "Pacific" },
    { id: "Pacific/Fakaofo", country: "Tokelau", region: "Pacific" },
    { id: "Pacific/Fiji", country: "Fiji", region: "Pacific" },
    { id: "Pacific/Funafuti", country: "Tuvalu", region: "Pacific" },
    { id: "Pacific/Galapagos", country: "Ecuador", region: "Pacific" },
    { id: "Pacific/Gambier", country: "French Polynesia", region: "Pacific" },
    { id: "Pacific/Guadalcanal", country: "Solomon Islands", region: "Pacific" },
    { id: "Pacific/Guam", country: "Guam", region: "Pacific" },
    { id: "Pacific/Honolulu", country: "United States", region: "Pacific" },
    { id: "Pacific/Kiritimati", country: "Kiribati", region: "Pacific" },
    { id: "Pacific/Kosrae", country: "Micronesia", region: "Pacific" },
    { id: "Pacific/Kwajalein", country: "Marshall Islands", region: "Pacific" },
    { id: "Pacific/Majuro", country: "Marshall Islands", region: "Pacific" },
    { id: "Pacific/Marquesas", country: "French Polynesia", region: "Pacific" },
    { id: "Pacific/Midway", country: "United States", region: "Pacific" },
    { id: "Pacific/Nauru", country: "Nauru", region: "Pacific" },
    { id: "Pacific/Niue", country: "Niue", region: "Pacific" },
    { id: "Pacific/Norfolk", country: "Norfolk Island", region: "Pacific" },
    { id: "Pacific/Noumea", country: "New Caledonia", region: "Pacific" },
    { id: "Pacific/Pago_Pago", country: "American Samoa", region: "Pacific" },
    { id: "Pacific/Palau", country: "Palau", region: "Pacific" },
    { id: "Pacific/Pitcairn", country: "Pitcairn Islands", region: "Pacific" },
    { id: "Pacific/Pohnpei", country: "Micronesia", region: "Pacific" },
    { id: "Pacific/Port_Moresby", country: "Papua New Guinea", region: "Pacific" },
    { id: "Pacific/Rarotonga", country: "Cook Islands", region: "Pacific" },
    { id: "Pacific/Saipan", country: "Northern Mariana Islands", region: "Pacific" },
    { id: "Pacific/Tahiti", country: "French Polynesia", region: "Pacific" },
    { id: "Pacific/Tarawa", country: "Kiribati", region: "Pacific" },
    { id: "Pacific/Tongatapu", country: "Tonga", region: "Pacific" },
    { id: "Pacific/Wake", country: "United States", region: "Pacific" },
    { id: "Pacific/Wallis", country: "Wallis and Futuna", region: "Pacific" }
];

const timezoneList = document.getElementById('timezoneList');
const searchInput = document.getElementById('searchInput');

function getOffset(timeZone) {
    try {
        const now = new Date();
        const str = now.toLocaleString('en-US', { timeZone, timeZoneName: 'longOffset' });
        const match = str.match(/GMT([+-]\d{2}:\d{2})/);
        return match ? match[1] : 'UTC+00:00';
    } catch (e) {
        return 'N/A';
    }
}

function renderTimezones(filter = '') {
    timezoneList.innerHTML = '';
    const filterLower = filter.toLowerCase();

    timezones.forEach(tz => {
        const city = tz.id.split('/').pop().replace(/_/g, ' ');
        const searchableText = `${tz.id} ${tz.country} ${tz.region} ${city}`.toLowerCase();

        if (searchableText.includes(filterLower)) {
            const row = document.createElement('div');
            row.className = 'table-row';
            
            const offset = getOffset(tz.id);

            row.innerHTML = `
                <div class="col" title="${tz.id}">${tz.id}</div>
                <div class="col" title="${tz.country}">${tz.country}</div>
                <div class="col" title="${city}">${city}</div>
                <div class="col"><span class="offset-badge">${offset}</span></div>
            `;
            timezoneList.appendChild(row);
        }
    });
}

// Initial render
renderTimezones();

// Search functionality
searchInput.addEventListener('input', (e) => {
    renderTimezones(e.target.value);
});
